image: maven:3.9.11-ibm-semeru-21-noble
# image: maven:3.9.11-eclipse-temurin-8

stages:
  - build
  - deploy

cache:
  paths:
    - .m2/repository/
    - pom.xml

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  # DOCKER_TLS_CERTDIR: ""
  MAVEN_REPO_URL: "https://repo.maven.apache.org/maven2"

build:
  stage: build
  script:
    # Install the provided JARs to local Maven repository
    - mvn install:install-file -Dfile=../JavaPOS/lib/javapos.jar -DgroupId=org.javapos -DartifactId=javapos -Dversion=1.14.1 -Dpackaging=jar
    - mvn install:install-file -Dfile=../JavaPOS/lib/epsonjpos.jar -DgroupId=com.epson -DartifactId=epsonjpos -Dversion=1.14.1 -Dpackaging=jar
    # Now run the build
    - mvn $MAVEN_CLI_OPTS -U --update-snapshots clean install
    - rm -rf pom.xml

deploy:
  only:
    - master
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS clean deploy
    - rm -rf pom.xml
