{
  "plugins": [
    "@semantic-release/commit-analyzer",
     ["@semantic-release/release-notes-generator", {
      "preset": "angular",
      "parserOpts": {
        "noteKeywords": ["BREAKING CHANGE", "BREAKING CHANGES", "BREAKING"]
      },
      "writerOpts": {
        "commitsSort": ["subject", "scope"]
      }
    }],
    "@semantic-release/changelog",
    ["@semantic-release/exec", {
      
      "prepareCmd": "mvn versions:set -DnewVersion=${nextRelease.version} && mvn versions:commit",
    }],
  
  ["@semantic-release/git",
  {"assets":["CHANGELOG.md", "pom.xml", "target/export/*.jar"],
      "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"}]
      ],
      
}